# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

use_modular_headers!

pod 'SnapKit', '~> 4.0'
pod 'RxSwift', '~> 5.0'
pod 'RxCocoa', '~> 5.0'

target 'RxExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxExample

  target 'RxExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxExampleUITests' do
    # Pods for testing
  end

end
